logging:
  file:
    name: C:/Users/Sreenivas Bandaru/Documents/loggerfile/logFile.log
  level:
    com:
      loggerfile: trace
    root: info
  logback:
    rollingpolicy:
      enabled: true
    #  file-name-pattern: logFile.%d{yyyy-mm-dd}.%i.log
      max-file-size: 5MB
      max-history: 5
      total-size-cap: 10MB
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n'
    
server:
  port: 8082
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/empproject
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: MANAGER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
